services:
  bacelar_api:
    build:
      context: .
      dockerfile: Dockerfile
    command: /code/start.sh
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
      - ./firebase-credentials.json:/code/firebase-credentials.json
      - ./alembic:/code/alembic
    env_file: .env
    depends_on:
      - bacelar_postgres
      - bacelar_redis
    networks:
      - bacelar_network

  bacelar_postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - bacelar_network

  bacelar_redis:
    image: redis:6-alpine
    networks:
      - bacelar_network
    
volumes:
  postgres_data:

networks:
  bacelar_network:
    driver: bridge