# alembic/script.py.mako

"""Add final fields to user/deadline and notification table

Revision ID: 28cf9d6eee95
Revises: 95bf224e3805
Create Date: 2025-07-29 01:45:42.915422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28cf9d6eee95'
down_revision = '95bf224e3805'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deadlines', sa.Column('type', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_deadlines_type'), 'deadlines', ['type'], unique=False)
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('notification_preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_preferences')
    op.drop_column('users', 'phone')
    op.drop_index(op.f('ix_deadlines_type'), table_name='deadlines')
    op.drop_column('deadlines', 'type')
    # ### end Alembic commands ###