# alembic/script.py.mako

"""Add notification model and API features for dashboard

Revision ID: 2f16c6f5350f
Revises: f410d4b18d5a
Create Date: 2025-07-31 02:21:03.500570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f16c6f5350f'
down_revision = 'f410d4b18d5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###