# alembic/script.py.mako

"""Add deadline and history tables

Revision ID: 55f0c0ef41bd
Revises: 
Create Date: 2025-07-22 01:57:20.509333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f0c0ef41bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('profile', sa.Enum('ADMIN', 'ADVOGADO', 'ESTAGIARIO', name='userprofile'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_cpf'), 'users', ['cpf'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('deadlines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('process_number', sa.String(length=100), nullable=True),
    sa.Column('parties', sa.Text(), nullable=True),
    sa.Column('task_description', sa.Text(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'CONCLUIDO', 'CANCELADO', name='deadlinestatus'), nullable=False),
    sa.Column('classification', sa.Enum('NORMAL', 'CRITICO', 'FATAL', name='deadlineclassification'), nullable=False),
    sa.Column('responsible_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deadlines_due_date'), 'deadlines', ['due_date'], unique=False)
    op.create_index(op.f('ix_deadlines_process_number'), 'deadlines', ['process_number'], unique=False)
    op.create_index(op.f('ix_deadlines_status'), 'deadlines', ['status'], unique=False)
    op.create_table('deadline_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action_description', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deadline_id', sa.UUID(), nullable=False),
    sa.Column('acting_user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['acting_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deadline_id'], ['deadlines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deadline_history')
    op.drop_index(op.f('ix_deadlines_status'), table_name='deadlines')
    op.drop_index(op.f('ix_deadlines_process_number'), table_name='deadlines')
    op.drop_index(op.f('ix_deadlines_due_date'), table_name='deadlines')
    op.drop_table('deadlines')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_cpf'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###