# alembic/script.py.mako

"""Add notifications table

Revision ID: 9d264b02bba8
Revises: 2f16c6f5350f
Create Date: 2025-07-31 17:24:45.705302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d264b02bba8'
down_revision = '2f16c6f5350f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###