# alembic/script.py.mako

"""Add notification model and API features for dashboard

Revision ID: f410d4b18d5a
Revises: 28cf9d6eee95
Create Date: 2025-07-31 02:12:05.372686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f410d4b18d5a'
down_revision = '28cf9d6eee95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###